name: Pacman Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Organize files
        run: |
          mkdir -p output
          mv dist/*.svg output/
          echo "Arquivos gerados:"
          ls -la output/

      - name: Update README
        run: |
          SVG_LIGHT="https://raw.githubusercontent.com/${{ github.repository }}/output/pacman-contribution-graph.svg?t=$(date +%s)"
          SVG_DARK="https://raw.githubusercontent.com/${{ github.repository }}/output/pacman-contribution-graph-dark.svg?t=$(date +%s)"
          
          HTML_CONTENT="<div align=\"center\">\n<picture>\n  <source media=\"(prefers-color-scheme: dark)\" srcset=\"$SVG_DARK\">\n  <source media=\"(prefers-color-scheme: light)\" srcset=\"$SVG_LIGHT\">\n  <img src=\"$SVG_LIGHT\" alt=\"Pacman eating contributions\" width=\"100%\">\n</picture>\n</div>"
          
          # Remove qualquer conteúdo existente do Pacman
          sed -i '/<div align="center">/,/<\/div>/d' README.md
          
          # Adiciona o novo conteúdo no final
          echo -e "\n$HTML_CONTENT" >> README.md
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Pacman animation [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
